### ISSUE TITLE
Usage from node

### ISSUE THREAD

**Issue by davazp** [nakardo/node-gameboy#7]
Hey!

I am trying to use this as a library from node installed with `npm`, however, the `lib` directory is not fully available in the generated package:

The bundle generated in `dist/` doesn't work with node nicely (uses `document`), and additionally `main` field in the `package.json` points to `lib/gameboy.js`.

Can we expose the `lib` directory with the package? 

Thanks!

**Comment by nakardo** [comment]
Thanks for spotting this!. Seems like it got broke on [this](https://github.com/nakardo/node-gameboy/commit/aeb4ec18078bb936ffcde158fad120f0e5661b03) commit. I'll make a quick fix asap and publish a patch with the rule to include the `lib` directory.

**Comment by nakardo** [comment]
Should be fixed on [v0.4.4](https://github.com/nakardo/node-gameboy/releases/tag/v0.4.4). Let me know if you've a chance to try it again. Gracias!

**Comment by davazp** [comment]
It works. Thanks!

Just to provide you with some context, we are working on a small Forth-based tool to develop games for the game boy, and we use this library to test our generated test roms.

We had to use some internals of the library, but it is fine for now, not a problem maintaining it if you decide to change it. Here is our project:

https://github.com/ams-hackers/dmg-forth

Thanks again!
